services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - './:/app'
      - './storage/app/public:/app/public/storage'
    depends_on:
      - web
    logging:
      options:
        max-size: '10M'
        max-file: '3'

  web:
    platform: linux/amd64
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    depends_on:
      - db
    logging:
      options:
        max-size: '10M'
        max-file: '3'

  db:
    image: postgres:17
    ports:
      - '${EXTERNAL_PGSQL_PORT:-5432}:5432'
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    logging:
      options:
        max-size: '10M'
        max-file: '3'

volumes:
  pgsql_data:
